displayUsage() {
	echo "36node -- dotfiles management"
	echo ""
	echo "Usage:"
	echo "  ./install.sh                完整安装（读取 install.conf；缺失则装全部 + 询问 extra）"
	echo "  ./install.sh <package>      仅安装单个 package（跳过系统引导和 brew 软件包）"
	echo "  ./install.sh -h             显示帮助"
	echo ""
	echo "Options:"
	echo "  -o, --overwrite   Overwrite file if it exists"
	echo "  -b, --backup      Backup file if it exists"
	echo "  -s, --skip        Skip file if it exists"
	echo "  -h, --help        Show this help message and exit"
	echo ""
	echo "配置文件（可选）："
	echo "  install.conf      控制 PACKAGES 列表与 INSTALL_EXTRA 开关，不进 git"
	echo "                    模板见 install.conf.example"
}
