model_provider = "linkapi"
model = "gpt-5.5"
model_reasoning_effort = "high"
network_access = "enabled"
sandbox_mode = "danger-full-access"
approval_policy = "never"
disable_response_storage = true
notify = [
    "/Users/zzs/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient",
    "turn-ended",
]
personality = "pragmatic"

[model_providers.linkapi]
name = "linkapi"
base_url = "https://api.linkapi.ai/v1"
wire_api = "responses"
requires_openai_auth = true

[projects."/Users/zzs"]
trust_level = "trusted"

[projects."/Users/zzs/Workspace/zzswang/hello-word"]
trust_level = "trusted"

[projects."/Users/zzs/Workspace/36node/seed-backend"]
trust_level = "trusted"

[projects."/Users/zzs/Workspace/adventurer-tech/adventurer-next"]
trust_level = "trusted"

[projects."/Users/zzs/Library/Mobile Documents/com~apple~CloudDocs/.dotfiles/.ssh"]
trust_level = "trusted"

[projects."/Users/zzs/Workspace/zzswang"]
trust_level = "trusted"

[projects."/Users/zzs/Workspace/haivivi/haivivi-next"]
trust_level = "trusted"

[projects."/Users/zzs/.dotfiles"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[tui.model_availability_nux]
"gpt-5.5" = 4

[marketplaces.openai-bundled]
last_updated = "2026-06-13T01:12:30Z"
source_type = "local"
source = "/Users/zzs/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-12T05:37:13Z"
source_type = "local"
source = "/Users/zzs/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[features]
js_repl = false
memories = true

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/zzs/.codex"
CODEX_HOME = "/Users/zzs/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "27dca86fd6b571c49414a4b78e46b57bcf683a46cd1319799c11fbb6cfae3110"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.609.41114"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[mcp_servers.chrome-devtools]
command = "npx"
args = [
    "chrome-devtools-mcp@latest",
    "--browserUrl",
    "http://127.0.0.1:9222",
]

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = true
appearanceTheme = "system"

[desktop.open-in-target-preferences]
global = "zed"

[desktop.open-in-target-preferences.perPath]
"/Users/zzs/Workspace/zzswang/hello-word" = "cursor"
"/Users/zzs/Workspace/adventurer-tech/adventurer-next" = "zed"

[memories]
generate_memories = true
use_memories = true
disable_on_external_context = true
